[package]
name = "nic-driver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sel4-microkit.workspace = true
virtio = { path = "../../crates/virtio" }
lfw-log = { path = "../../crates/log" }
pd-runtime = { path = "../../crates/pd-runtime" }
wire = { path = "../../crates/wire" }
nic-driver-core = { path = "../../crates/nic-driver-core" }
lfw-metrics = { path = "../../crates/metrics" }

[lints]
workspace = true
