[package]
name = "config-pd"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sel4-microkit.workspace = true
config = { path = "../../crates/config" }
lfw-log = { path = "../../crates/log" }
pd-runtime = { path = "../../crates/pd-runtime" }
wire = { path = "../../crates/wire" }
lfw-metrics = { path = "../../crates/metrics" }

[lints]
workspace = true
